### ISSUE TITLE
项目启动都报一大推错误,页面一片白

### ISSUE THREAD

**Issue by r692802421** [vuejs/docs-next-zh-cn#158]

**Comment by r692802421** [comment]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to resolve async component: function Layout() {
    return Promise.all(/*! import() */[__webpack_require__.e(8), __webpack_require__.e(7)]).then(__webpack_require__.bind(null, /*! ./src/.vuepress/theme/layouts/Layout.vue */ "./src/.vuepress/theme/layouts/Layout.vue"));
  }
Reason: Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\node-sass\vendor\win32-x64-64\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at getDefaultSassImplementation (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\sass-loader\dist\getDefaultSassImplementation.js:24:10)
    at getSassImplementation (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\sass-loader\dist\getSassImplementation.js:19:72)
    at Object.loader (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\sass-loader\dist\index.js:40:61)
warn @ vue.runtime.esm.js?2b0e:619
eval @ vue.runtime.esm.js?2b0e:3676
eval @ vue.runtime.esm.js?2b0e:336
Promise.then (async)
resolveAsyncComponent @ vue.runtime.esm.js?2b0e:3692
createComponent @ vue.runtime.esm.js?2b0e:3200
_createElement @ vue.runtime.esm.js?2b0e:3434
createElement @ vue.runtime.esm.js?2b0e:3353
vm._c @ vue.runtime.esm.js?2b0e:3491
render @ GlobalLayout.vue?2170:5
Vue._render @ vue.runtime.esm.js?2b0e:3548
updateComponent @ vue.runtime.esm.js?2b0e:4066
get @ vue.runtime.esm.js?2b0e:4479
Watcher @ vue.runtime.esm.js?2b0e:4468
mountComponent @ vue.runtime.esm.js?2b0e:4073
Vue.$mount @ vue.runtime.esm.js?2b0e:8415
init @ vue.runtime.esm.js?2b0e:3118
merged @ vue.runtime.esm.js?2b0e:3301
createComponent @ vue.runtime.esm.js?2b0e:5978
createElm @ vue.runtime.esm.js?2b0e:5925
createChildren @ vue.runtime.esm.js?2b0e:6053
createElm @ vue.runtime.esm.js?2b0e:5954
patch @ vue.runtime.esm.js?2b0e:6516
Vue._update @ vue.runtime.esm.js?2b0e:3945
updateComponent @ vue.runtime.esm.js?2b0e:4066
get @ vue.runtime.esm.js?2b0e:4479
Watcher @ vue.runtime.esm.js?2b0e:4468
mountComponent @ vue.runtime.esm.js?2b0e:4073
Vue.$mount @ vue.runtime.esm.js?2b0e:8415
eval @ clientEntry.js?3501:12
eval @ vue-router.esm.js?8c4f:2167
eval @ vue-router.esm.js?8c4f:2166
eval @ vue-router.esm.js?8c4f:2294
step @ vue-router.esm.js?8c4f:1895
step @ vue-router.esm.js?8c4f:1902
runQueue @ vue-router.esm.js?8c4f:1906
eval @ vue-router.esm.js?8c4f:2289
step @ vue-router.esm.js?8c4f:1895
eval @ vue-router.esm.js?8c4f:1899
eval @ vue-router.esm.js?8c4f:2274
eval @ vue-router.esm.js?8c4f:2055
iterator @ vue-router.esm.js?8c4f:2252
step @ vue-router.esm.js?8c4f:1898
eval @ vue-router.esm.js?8c4f:1899
eval @ vue-router.esm.js?8c4f:2274
Promise.then (async)
beforeEnter @ routes.js?fc18:16
iterator @ vue-router.esm.js?8c4f:2252
step @ vue-router.esm.js?8c4f:1898
eval @ vue-router.esm.js?8c4f:1899
eval @ vue-router.esm.js?8c4f:2274
eval @ redirect.js?605e:26
iterator @ vue-router.esm.js?8c4f:2252
step @ vue-router.esm.js?8c4f:1898
runQueue @ vue-router.esm.js?8c4f:1906
confirmTransition @ vue-router.esm.js?8c4f:2282
transitionTo @ vue-router.esm.js?8c4f:2152
init @ vue-router.esm.js?8c4f:2910
beforeCreate @ vue-router.esm.js?8c4f:1240
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4219
Vue._init @ vue.runtime.esm.js?2b0e:5004
Vue @ vue.runtime.esm.js?2b0e:5085
_callee$ @ app.js?63b8:102
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
_createApp @ app.js?63b8:62
createApp @ app.js?63b8:62
eval @ clientEntry.js?3501:10
./node_modules/@vuepress/core/lib/client/clientEntry.js @ app.js:1403
__webpack_require__ @ app.js:833
fn @ app.js:130
0 @ app.js:5422
__webpack_require__ @ app.js:833
(anonymous) @ app.js:971
(anonymous) @ app.js:974
Show 14 more frames
client?cae4:150 [WDS] Errors while compiling. Reload prevented.
errors @ client?cae4:150
eval @ socket.js?e29c:47
sock.onmessage @ SockJSClient.js?0a33:67
EventTarget.dispatchEvent @ sockjs.js?9be2:170
eval @ sockjs.js?9be2:888
SockJS._transportMessage @ sockjs.js?9be2:886
EventEmitter.emit @ sockjs.js?9be2:86
WebSocketTransport.ws.onmessage @ sockjs.js?9be2:2962
client?cae4:159 ./src/.vuepress/components/community/themes/theme-item.vue?vue&type=style&index=0&id=980a6dcc&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--10-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/.vuepress/components/community/themes/theme-item.vue?vue&type=style&index=0&id=980a6dcc&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\node-sass\vendor\win32-x64-64\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at getDefaultSassImplementation (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\sass-loader\dist\getDefaultSassImplementation.js:24:10)
    at getSassImplementation (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\sass-loader\dist\getSassImplementation.js:19:72)
    at Object.loader (E:\Myjob\project\vue\vue3\docs-next-zh-cn\node_modules\sass-loader\dist\index.js:40:61)

**Comment by r692802421** [comment]
控制台26个报错

**Comment by veaba** [comment]
@r692802421  你好，请通过其他方式来解决该问题，确保在安装依赖过程中没有出现其他错误问题。

刚重新 clone 也未出现，现在将close 该 issue。

（提示：可以使用 cnpm 确保 node-sass 能够安装成功。）
